/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type AddReview = {
    addReview: ({
        id: string;
    }) | null;
};
export type AddReviewVariables = {
    pid: string;
    commentBody: string;
};
