/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ProductReviewFragment = {
    reviews: ({
        id: string;
        commentBody: string;
    })[];
};
