/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ProductsQuery = {
    products: ({
        id: string;
        name: string;
    })[];
};
export type ProductsQueryVariables = {};
